// This file is auto-generated by fetch-strapi-content.js
// Do not edit manually - run 'npm run fetch-content' to update

import type { StrapiHeader, StrapiFooter, StrapiHero, StrapiCarouselItem, StrapiAboutPage } from './strapi-types';

export const strapiContent = {
  "header": {
    "id": 4,
    "documentId": "s9pqryf05kdg65gzmtoxrs4v",
    "createdAt": "2025-08-22T20:47:13.762Z",
    "updatedAt": "2025-08-25T08:39:04.650Z",
    "publishedAt": "2025-08-25T08:39:04.663Z",
    "logo": {
      "id": 12,
      "documentId": "rupfh6mbkil6y8aanu95lu9w",
      "name": "stock-vector-cannabis-plant-icon-with-shadow-on-transparent-background-hemp-narcotic-sign-symbol-green-747238999.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 1500,
      "height": 1600,
      "formats": {
        "thumbnail": {
          "name": "thumbnail_stock-vector-cannabis-plant-icon-with-shadow-on-transparent-background-hemp-narcotic-sign-symbol-green-747238999.jpg",
          "hash": "thumbnail_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643",
          "ext": ".jpg",
          "mime": "image/jpeg",
          "path": null,
          "width": 146,
          "height": 156,
          "size": 6.83,
          "sizeInBytes": 6827,
          "url": "/uploads/thumbnail_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643.jpg"
        },
        "small": {
          "name": "small_stock-vector-cannabis-plant-icon-with-shadow-on-transparent-background-hemp-narcotic-sign-symbol-green-747238999.jpg",
          "hash": "small_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643",
          "ext": ".jpg",
          "mime": "image/jpeg",
          "path": null,
          "width": 469,
          "height": 500,
          "size": 50.13,
          "sizeInBytes": 50128,
          "url": "/uploads/small_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643.jpg"
        },
        "medium": {
          "name": "medium_stock-vector-cannabis-plant-icon-with-shadow-on-transparent-background-hemp-narcotic-sign-symbol-green-747238999.jpg",
          "hash": "medium_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643",
          "ext": ".jpg",
          "mime": "image/jpeg",
          "path": null,
          "width": 703,
          "height": 750,
          "size": 87.69,
          "sizeInBytes": 87686,
          "url": "/uploads/medium_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643.jpg"
        },
        "large": {
          "name": "large_stock-vector-cannabis-plant-icon-with-shadow-on-transparent-background-hemp-narcotic-sign-symbol-green-747238999.jpg",
          "hash": "large_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643",
          "ext": ".jpg",
          "mime": "image/jpeg",
          "path": null,
          "width": 938,
          "height": 1000,
          "size": 129.07,
          "sizeInBytes": 129070,
          "url": "/uploads/large_stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643.jpg"
        }
      },
      "hash": "stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 248.75,
      "url": "/uploads/stock_vector_cannabis_plant_icon_with_shadow_on_transparent_background_hemp_narcotic_sign_symbol_green_747238999_c819a95643.jpg",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "createdAt": "2025-08-25T08:39:00.139Z",
      "updatedAt": "2025-08-25T08:39:00.139Z",
      "publishedAt": "2025-08-25T08:39:00.139Z"
    },
    "navigation": [
      {
        "id": 23,
        "label": "Shop",
        "url": "/shop",
        "target": "_self",
        "icon": null
      },
      {
        "id": 24,
        "label": "About",
        "url": "/about",
        "target": "_self",
        "icon": null
      },
      {
        "id": 25,
        "label": "Locations",
        "url": "/locations",
        "target": "_self",
        "icon": null
      },
      {
        "id": 26,
        "label": "Contact",
        "url": "/contact",
        "target": "_self",
        "icon": null
      }
    ],
    "ctaButton": [
      {
        "id": 15,
        "label": "Order Now",
        "url": "/shop",
        "variant": "primary"
      }
    ]
  },
  "footer": {
    "id": 2,
    "documentId": "kqjqb3xdw5z60bgmrmooh1eh",
    "description": "Your trusted cannabis dispensary",
    "createdAt": "2025-08-23T06:20:31.484Z",
    "updatedAt": "2025-08-23T06:23:24.633Z",
    "publishedAt": "2025-08-23T06:23:24.642Z",
    "copyright": "© 2024 Your Store. All rights reserved.",
    "socialLinks": [
      {
        "id": 3,
        "platform": "instagram",
        "url": "https://instagram.com/yourstore"
      },
      {
        "id": 4,
        "platform": "facebook",
        "url": "https://facebook.com/yourstore"
      }
    ],
    "sections": [
      {
        "id": 3,
        "title": "Shop"
      },
      {
        "id": 4,
        "title": "Company"
      }
    ]
  },
  "hero": {
    "id": 6,
    "documentId": "i3zvtqndcgufd65va6eubs9u",
    "title": "Welcome to Premium Cannabis Pulkit",
    "subtitle": "Discover our curated selection",
    "backgroundColor": "#1a1a1a",
    "createdAt": "2025-08-23T06:24:56.321Z",
    "updatedAt": "2025-08-23T07:48:59.675Z",
    "publishedAt": "2025-08-23T07:48:59.683Z",
    "overlay": false,
    "overlayOpacity": null,
    "backgroundImage": {
      "id": 6,
      "documentId": "jwqlp07rc3srcpvdi8g7l2mz",
      "name": "Rectangle 77.png",
      "alternativeText": null,
      "caption": null,
      "width": 1200,
      "height": 675,
      "formats": {
        "thumbnail": {
          "name": "thumbnail_Rectangle 77.png",
          "hash": "thumbnail_Rectangle_77_122da64690",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 245,
          "height": 138,
          "size": 84.64,
          "sizeInBytes": 84636,
          "url": "/uploads/thumbnail_Rectangle_77_122da64690.png"
        },
        "small": {
          "name": "small_Rectangle 77.png",
          "hash": "small_Rectangle_77_122da64690",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 500,
          "height": 281,
          "size": 323.39,
          "sizeInBytes": 323394,
          "url": "/uploads/small_Rectangle_77_122da64690.png"
        },
        "medium": {
          "name": "medium_Rectangle 77.png",
          "hash": "medium_Rectangle_77_122da64690",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 750,
          "height": 422,
          "size": 708.7,
          "sizeInBytes": 708697,
          "url": "/uploads/medium_Rectangle_77_122da64690.png"
        },
        "large": {
          "name": "large_Rectangle 77.png",
          "hash": "large_Rectangle_77_122da64690",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 1000,
          "height": 563,
          "size": 1243.33,
          "sizeInBytes": 1243331,
          "url": "/uploads/large_Rectangle_77_122da64690.png"
        }
      },
      "hash": "Rectangle_77_122da64690",
      "ext": ".png",
      "mime": "image/png",
      "size": 369.51,
      "url": "/uploads/Rectangle_77_122da64690.png",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "createdAt": "2025-08-23T07:33:44.648Z",
      "updatedAt": "2025-08-23T07:48:56.084Z",
      "publishedAt": "2025-08-23T07:33:44.649Z"
    },
    "ctaButtons": [
      {
        "id": 13,
        "label": "Shop Now",
        "url": "/shop",
        "variant": "primary"
      },
      {
        "id": 14,
        "label": "Learn More",
        "url": "/about",
        "variant": "outline"
      }
    ]
  },
  "carousel": [
    {
      "id": 9,
      "documentId": "pm5e2yhynskjg9mqdyt07lch",
      "createdAt": "2025-08-23T06:26:35.001Z",
      "updatedAt": "2025-08-25T08:06:46.886Z",
      "publishedAt": "2025-08-25T08:06:46.893Z",
      "title": "New Arrivals",
      "description": "Check out our latest products",
      "order": 1,
      "active": true,
      "image": {
        "id": 9,
        "documentId": "e8rfuj7qri2xi822srfc8oht",
        "name": "6711d450a9e995b7c007a588_PLUGPLAY-BONANZA-$40-550h.avif",
        "alternativeText": null,
        "caption": null,
        "width": null,
        "height": null,
        "formats": null,
        "hash": "6711d450a9e995b7c007a588_PLUGPLAY_BONANZA_40_550h_829629834c",
        "ext": ".avif",
        "mime": "image/avif",
        "size": 38.49,
        "url": "/uploads/6711d450a9e995b7c007a588_PLUGPLAY_BONANZA_40_550h_829629834c.avif",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-25T08:06:22.850Z",
        "updatedAt": "2025-08-25T08:06:22.850Z",
        "publishedAt": "2025-08-25T08:06:22.851Z"
      },
      "link": [
        {
          "id": 9,
          "label": "Shop New",
          "url": "/shop/new",
          "target": "_self",
          "icon": null
        }
      ]
    },
    {
      "id": 10,
      "documentId": "rb3ny8o1keuw386gc98l129h",
      "createdAt": "2025-08-23T07:40:05.668Z",
      "updatedAt": "2025-08-25T08:07:10.993Z",
      "publishedAt": "2025-08-25T08:07:11.000Z",
      "title": "Best seller",
      "description": "best selling products",
      "order": 2,
      "active": true,
      "image": {
        "id": 10,
        "documentId": "nq925rfpg668jclz2t1pckcn",
        "name": "671c037f506bc20f72aa5f69_885x580-FTP-Deal-Harvest-Cannabis.jpg",
        "alternativeText": null,
        "caption": null,
        "width": 885,
        "height": 580,
        "formats": {
          "thumbnail": {
            "name": "thumbnail_671c037f506bc20f72aa5f69_885x580-FTP-Deal-Harvest-Cannabis.jpg",
            "hash": "thumbnail_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "path": null,
            "width": 238,
            "height": 156,
            "size": 9.01,
            "sizeInBytes": 9012,
            "url": "/uploads/thumbnail_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252.jpg"
          },
          "small": {
            "name": "small_671c037f506bc20f72aa5f69_885x580-FTP-Deal-Harvest-Cannabis.jpg",
            "hash": "small_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "path": null,
            "width": 500,
            "height": 328,
            "size": 33,
            "sizeInBytes": 33002,
            "url": "/uploads/small_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252.jpg"
          },
          "medium": {
            "name": "medium_671c037f506bc20f72aa5f69_885x580-FTP-Deal-Harvest-Cannabis.jpg",
            "hash": "medium_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "path": null,
            "width": 750,
            "height": 492,
            "size": 66.31,
            "sizeInBytes": 66306,
            "url": "/uploads/medium_671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252.jpg"
          }
        },
        "hash": "671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252",
        "ext": ".jpg",
        "mime": "image/jpeg",
        "size": 87.3,
        "url": "/uploads/671c037f506bc20f72aa5f69_885x580_FTP_Deal_Harvest_Cannabis_1cead79252.jpg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-25T08:06:22.907Z",
        "updatedAt": "2025-08-25T08:06:22.907Z",
        "publishedAt": "2025-08-25T08:06:22.907Z"
      },
      "link": [
        {
          "id": 10,
          "label": "Shop New",
          "url": "/shop/new",
          "target": null,
          "icon": null
        }
      ]
    },
    {
      "id": 11,
      "documentId": "lulzd5fulxagdy2kafnzxulf",
      "createdAt": "2025-08-25T07:25:20.963Z",
      "updatedAt": "2025-08-25T08:07:24.128Z",
      "publishedAt": "2025-08-25T08:07:24.135Z",
      "title": "Bringing Harvest Closer",
      "description": "Bringing Harvest Closer: Expanding to More Cities Near You!",
      "order": 3,
      "active": true,
      "image": {
        "id": 11,
        "documentId": "slfuoqccb6z5tcaku0xg2ufh",
        "name": "67185ce2448f59b7f3a1978c_Harvest of Santa Monica is Growing—Coming Soon to New Cities Near You!.avif",
        "alternativeText": null,
        "caption": null,
        "width": null,
        "height": null,
        "formats": null,
        "hash": "67185ce2448f59b7f3a1978c_Harvest_of_Santa_Monica_is_Growing_Coming_Soon_to_New_Cities_Near_You_96807349f5",
        "ext": ".avif",
        "mime": "image/avif",
        "size": 20.63,
        "url": "/uploads/67185ce2448f59b7f3a1978c_Harvest_of_Santa_Monica_is_Growing_Coming_Soon_to_New_Cities_Near_You_96807349f5.avif",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-25T08:06:57.973Z",
        "updatedAt": "2025-08-25T08:06:57.973Z",
        "publishedAt": "2025-08-25T08:06:57.973Z"
      },
      "link": [
        {
          "id": 11,
          "label": "Shop New",
          "url": "/shop/new",
          "target": "_self",
          "icon": null
        }
      ]
    }
  ],
  "introSection": {
    "id": 3,
    "documentId": "x090fa1z0sksyc7deanqt34i",
    "title": "WELCOME TO HARVEST CANNABIS, YOUR TRUSTED CANNABIS DISPENSARY OFFERING A FRIENDLY SHOPPING EXPERIENCE AND A CURATED SELECTION OF PREMIUM CANNABIS PRODUCTS.",
    "content": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "text": "At Harvest Cannabis",
            "bold": true
          },
          {
            "type": "text",
            "text": ", we offer a world-class cannabis retail experience tailored to meet your unique preferences and needs. Our expert team is dedicated to curating, delivering, and scaling a premium selection of flowers, edibles, and concentrates, ensuring the utmost satisfaction for our customers. We believe the truest measure of our success is the loyalty and trust our clients place in us, which is why over half of our visitors become repeat customers. Join us and experience why Harvest of Santa Monica is the preferred choice for cannabis connoisseurs."
          }
        ]
      }
    ],
    "layout": "images-bottom",
    "titleStyle": "small",
    "contentAlignment": "left",
    "backgroundColor": "#ffffff",
    "padding": null,
    "createdAt": "2025-08-25T11:14:06.188Z",
    "updatedAt": "2025-08-25T11:34:36.739Z",
    "publishedAt": "2025-08-25T11:34:36.750Z",
    "images": [
      {
        "id": 14,
        "documentId": "pco49bb4rax70npn3lifar6c",
        "name": "6712bccf5cec05d78d86e295_Harvest-Of-Santa-Monica-Store-(4)1..2.avif",
        "alternativeText": null,
        "caption": null,
        "width": null,
        "height": null,
        "formats": null,
        "hash": "6712bccf5cec05d78d86e295_Harvest_Of_Santa_Monica_Store_4_1_2_91346362c9",
        "ext": ".avif",
        "mime": "image/avif",
        "size": 25.75,
        "url": "/uploads/6712bccf5cec05d78d86e295_Harvest_Of_Santa_Monica_Store_4_1_2_91346362c9.avif",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-25T11:12:13.871Z",
        "updatedAt": "2025-08-25T11:12:13.871Z",
        "publishedAt": "2025-08-25T11:12:13.871Z"
      },
      {
        "id": 13,
        "documentId": "tqaow6ddh5wflil1seyq4pn1",
        "name": "6712bccf7b1e01b2371351f2_Harvest-Of-Santa-Monica-Store-(63)1.3.avif",
        "alternativeText": null,
        "caption": null,
        "width": null,
        "height": null,
        "formats": null,
        "hash": "6712bccf7b1e01b2371351f2_Harvest_Of_Santa_Monica_Store_63_1_3_676e67e0b0",
        "ext": ".avif",
        "mime": "image/avif",
        "size": 20.89,
        "url": "/uploads/6712bccf7b1e01b2371351f2_Harvest_Of_Santa_Monica_Store_63_1_3_676e67e0b0.avif",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-25T11:12:00.464Z",
        "updatedAt": "2025-08-25T11:12:00.464Z",
        "publishedAt": "2025-08-25T11:12:00.464Z"
      }
    ],
    "ctaButton": [
      {
        "id": 18,
        "label": "KNOW MORE US →",
        "url": "/about",
        "variant": "outline"
      }
    ]
  }
} as {
  header: StrapiHeader | null;
  footer: StrapiFooter | null;
  hero: StrapiHero | null;
  carousel: StrapiCarouselItem[];
  introSection: any | null;
};

// Export fetched content
export { strapiContent };
