// This file is auto-generated by fetch-strapi-content.js
// Do not edit manually - run 'npm run fetch-content' to update

import type { StrapiHeader, StrapiFooter, StrapiHero, StrapiCarouselItem, StrapiAboutPage } from './strapi-types';

export const strapiContent = {
  "header": {
    "id": 3,
    "documentId": "s9pqryf05kdg65gzmtoxrs4v",
    "createdAt": "2025-08-22T20:47:13.762Z",
    "updatedAt": "2025-08-22T20:49:52.349Z",
    "publishedAt": "2025-08-22T20:49:52.362Z",
    "logo": {
      "id": 1,
      "documentId": "j93jdwob44bht1uel15oct3t",
      "name": "QR_Demo.png",
      "alternativeText": null,
      "caption": null,
      "width": 300,
      "height": 300,
      "formats": {
        "thumbnail": {
          "name": "thumbnail_QR_Demo.png",
          "hash": "thumbnail_QR_Demo_4ff460128a",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 156,
          "height": 156,
          "size": 13,
          "sizeInBytes": 12998,
          "url": "/uploads/thumbnail_QR_Demo_4ff460128a.png"
        }
      },
      "hash": "QR_Demo_4ff460128a",
      "ext": ".png",
      "mime": "image/png",
      "size": 1.49,
      "url": "/uploads/QR_Demo_4ff460128a.png",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "createdAt": "2025-08-22T14:27:54.991Z",
      "updatedAt": "2025-08-22T14:27:54.991Z",
      "publishedAt": "2025-08-22T14:27:54.991Z"
    },
    "navigation": [
      {
        "id": 9,
        "label": "Shop",
        "url": "/shop",
        "target": "_self",
        "icon": null
      },
      {
        "id": 10,
        "label": "About",
        "url": "/about",
        "target": "_self",
        "icon": null
      },
      {
        "id": 11,
        "label": "Locations",
        "url": "/locations",
        "target": "_self",
        "icon": null
      },
      {
        "id": 12,
        "label": "Contact",
        "url": "/contact",
        "target": "_self",
        "icon": null
      }
    ],
    "ctaButton": [
      {
        "id": 2,
        "label": "Order Now",
        "url": "/shop",
        "variant": "primary"
      }
    ]
  },
  "footer": {
    "id": 2,
    "documentId": "kqjqb3xdw5z60bgmrmooh1eh",
    "description": "Your trusted cannabis dispensary",
    "createdAt": "2025-08-23T06:20:31.484Z",
    "updatedAt": "2025-08-23T06:23:24.633Z",
    "publishedAt": "2025-08-23T06:23:24.642Z",
    "copyright": "© 2024 Your Store. All rights reserved.",
    "socialLinks": [
      {
        "id": 3,
        "platform": "instagram",
        "url": "https://instagram.com/yourstore"
      },
      {
        "id": 4,
        "platform": "facebook",
        "url": "https://facebook.com/yourstore"
      }
    ],
    "sections": [
      {
        "id": 3,
        "title": "Shop"
      },
      {
        "id": 4,
        "title": "Company"
      }
    ]
  },
  "hero": {
    "id": 2,
    "documentId": "i3zvtqndcgufd65va6eubs9u",
    "title": "Welcome to Premium Cannabis Pulkit",
    "subtitle": "Discover our curated selection",
    "backgroundColor": "#1a1a1a",
    "createdAt": "2025-08-23T06:24:56.321Z",
    "updatedAt": "2025-08-23T06:24:57.260Z",
    "publishedAt": "2025-08-23T06:24:57.267Z",
    "overlay": false,
    "overlayOpacity": null,
    "backgroundImage": {
      "id": 2,
      "documentId": "g0ayo9cr7dl5dal2t1da1sps",
      "name": "Rectangle 77.png",
      "alternativeText": null,
      "caption": null,
      "width": 254,
      "height": 265,
      "formats": {
        "thumbnail": {
          "name": "thumbnail_Rectangle 77.png",
          "hash": "thumbnail_Rectangle_77_e2438b4c15",
          "ext": ".png",
          "mime": "image/png",
          "path": null,
          "width": 150,
          "height": 156,
          "size": 61.35,
          "sizeInBytes": 61352,
          "url": "/uploads/thumbnail_Rectangle_77_e2438b4c15.png"
        }
      },
      "hash": "Rectangle_77_e2438b4c15",
      "ext": ".png",
      "mime": "image/png",
      "size": 52.57,
      "url": "/uploads/Rectangle_77_e2438b4c15.png",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "createdAt": "2025-08-22T14:30:15.738Z",
      "updatedAt": "2025-08-22T20:39:27.465Z",
      "publishedAt": "2025-08-22T14:30:15.738Z"
    },
    "ctaButtons": [
      {
        "id": 5,
        "label": "Shop Now",
        "url": "/shop",
        "variant": "primary"
      },
      {
        "id": 6,
        "label": "Learn More",
        "url": "/about",
        "variant": "outline"
      }
    ]
  },
  "carousel": [
    {
      "id": 2,
      "documentId": "pm5e2yhynskjg9mqdyt07lch",
      "createdAt": "2025-08-23T06:26:35.001Z",
      "updatedAt": "2025-08-23T06:30:03.589Z",
      "publishedAt": "2025-08-23T06:30:03.597Z",
      "title": "New Arrivals",
      "description": "Check out our latest products",
      "order": 1,
      "active": true,
      "image": {
        "id": 3,
        "documentId": "uqz6euojo9fkdtv3jn6xohse",
        "name": "2025-01-24T11_08_24.172Z_media.jpeg",
        "alternativeText": null,
        "caption": null,
        "width": 1236,
        "height": 507,
        "formats": {
          "thumbnail": {
            "name": "thumbnail_2025-01-24T11_08_24.172Z_media.jpeg",
            "hash": "thumbnail_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "path": null,
            "width": 245,
            "height": 100,
            "size": 5.36,
            "sizeInBytes": 5363,
            "url": "/uploads/thumbnail_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6.jpeg"
          },
          "large": {
            "name": "large_2025-01-24T11_08_24.172Z_media.jpeg",
            "hash": "large_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "path": null,
            "width": 1000,
            "height": 410,
            "size": 46.5,
            "sizeInBytes": 46495,
            "url": "/uploads/large_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6.jpeg"
          },
          "small": {
            "name": "small_2025-01-24T11_08_24.172Z_media.jpeg",
            "hash": "small_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "path": null,
            "width": 500,
            "height": 205,
            "size": 16.45,
            "sizeInBytes": 16452,
            "url": "/uploads/small_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6.jpeg"
          },
          "medium": {
            "name": "medium_2025-01-24T11_08_24.172Z_media.jpeg",
            "hash": "medium_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "path": null,
            "width": 750,
            "height": 308,
            "size": 29.2,
            "sizeInBytes": 29199,
            "url": "/uploads/medium_2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6.jpeg"
          }
        },
        "hash": "2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6",
        "ext": ".jpeg",
        "mime": "image/jpeg",
        "size": 65.39,
        "url": "/uploads/2025_01_24_T11_08_24_172_Z_media_f3d8f7ccc6.jpeg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2025-08-23T06:25:57.224Z",
        "updatedAt": "2025-08-23T06:25:57.224Z",
        "publishedAt": "2025-08-23T06:25:57.224Z"
      },
      "link": [
        {
          "id": 2,
          "label": "Shop New",
          "url": "/shop/new",
          "target": "_self",
          "icon": null
        }
      ]
    }
  ]
} as {
  header: StrapiHeader | null;
  footer: StrapiFooter | null;
  hero: StrapiHero | null;
  carousel: StrapiCarouselItem[];
};

// Export fetched content
export { strapiContent };
